/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;

import java.util.List;
import management.dto.ScannedUserResponse;
import management.model.ContentResponse;
import management.utils.APIs;
import management.utils.Service;
import org.springframework.data.domain.Page;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import sun.rmi.runtime.Log;

/**
 *
 * @author junie
 */
public class ScannedUserTable extends javax.swing.JFrame {
    private Service service;
    private int pageNumber = 0;
    private int pageSize = 10;
    private List<ScannedUserResponse> ScannedUserByEstablishmentList;
    /**
     * Creates new form ScannedUserTable
     */
    public ScannedUserTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Contact Tracing");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton1)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // pag pinindot ni user to, icacall ng function na to yung api, 
        // TODO kailangan mong gumawa ng table para dito
        // TODO kailangan mong ikalat sa table yung data na makukuha mo sa api
        // TODO goodluck hahah gang dito lang gagawin ko, sa pagcacall ng api
        // kailangan mo din iset yung pagination
        // gawa ka button na magiincrement ng pageNumber at pageSize
        
        
        // incase na makalimutan ko eto yung mga version ng jar file na ginamit ko
        /*
            conventer-gson- 2.9.0
            retrofit-2.9.0
            springframework.data.core_1.3.1.release.jar // d ko ren naman ginamit.
            okhttp-3.14.0
            okhttp-dnsoverhttps-3.14.0
            okio-1.17.2
            gson-2.6.2
        */
        this.service = APIs.getService();
        Call<ContentResponse> call = this.service.getAllScannedByEstablishment(this.pageNumber, this.pageSize);
        call.enqueue(new Callback<ContentResponse>() {
            @Override
            public void onFailure(Call<ContentResponse> call, Throwable t) {
                System.out.println(t.getMessage()); // madalas na makukuhang error is time out ibigsahin non sa server may problema, kaya ganon kasi nagsstart pa lang yung server, 
                // wala kasing natatanggap na request kaya nagshutdown na muna yung server,
            }

            @Override
            public void onResponse(Call<ContentResponse> call, Response<ContentResponse> response) {
               if(response.isSuccessful()) {
                ScannedUserByEstablishmentList = response.body().getContent(); // eto yung ikakalat mo sa table mo list yan
                System.out.println("Success");
               }
               else{
                   System.out.println(response.code()); // error code to, pag 500 ibigsabihin sa server may problema hindi sa client side
                   // pag 400 error code ibigsahin bad request sa client side which means sa code mo ang may problem, to be specific, mali yung endpoint na nainsert sa ginawang call
                   // marami pang error pero most likely hindi naman mageerror
               }
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScannedUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScannedUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScannedUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScannedUserTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScannedUserTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
